version: '3.8'

services:
  chroma_db:
    image: chromadb/chroma
    expose:
      - "8000"
    volumes:
      - chroma-data:/chroma/chroma
    environment:
      - CHROMA_SERVER_AUTH_CREDENTIALS_PROVIDER=chromadb.auth.token.TokenConfigServerAuthCredentialsProvider
      - CHROMA_SERVER_AUTH_PROVIDER=chromadb.auth.token.TokenAuthServerProvider
      - ANONYMIZED_TELEMETRY=False
      - IS_PERSISTENT=true
    env_file:
      - .env
  nuxt_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - "chroma_db"
    ports:
      - "5454:3000"
    environment:
      - NUXT_CHROMADB_URL=http://chroma_db:8000
    env_file:
      - .env

volumes:
  chroma-data:
    driver: local
